version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: "daily"
    groups:
      docker:
        patterns:
          - "*"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: "daily"
    groups:
      gomod-minor-patch:
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Incompatibility with Kubernetes, we can remove this once Kubernetes upgrades package. Some
      # The deprecated UnaryServerInterceptor and UnaryClientInterceptor function was removed in v0.61.0.
      - dependency-name: "go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
        versions: [">=0.61.0"]
    open-pull-requests-limit: 5
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: pip
    directory: /.github/workflows
    schedule:
      interval: "daily"
    groups:
      pip:
        patterns:
          - "*"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "build"
      include: "scope"
