repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: dist
  - id: check-yaml
    args:
    - --allow-multiple-documents
    exclude: charts/latest/templates # chart templates are not valid yaml
  - id: check-xml
  - id: check-json
- repo: https://github.com/golangci/golangci-lint
  rev: 6d2288e072e6f9c9bca28180cae9ce58a049c912 # v2.13.1
  hooks:
  - id: golangci-lint-full
- repo: https://github.com/hadolint/hadolint
  rev: 2eece55955ced00200be9729e9728cb7dacca505 # v2.15.1
  hooks:
    - id: hadolint-docker
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: 5b5dddc4fb0f83c3ea1fc5616fa63e115dce83e0 # v0.49.1
  hooks:
  - id: markdownlint-fix-docker
- repo: https://github.com/pycqa/flake8
  rev: c48217e1fc006c2dddd14df54e83b67da15de5cd # 7.3.0
  hooks:
  - id: flake8
- repo: https://github.com/codespell-project/codespell
  rev: 57b21406f092110c18776e39b0bda50d37c945c8 # v2.4.3
  hooks:
  - id: codespell
    args:
    - --config=.codespellrc
- repo: https://github.com/rhysd/actionlint
  rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
  hooks:
  - id: actionlint-docker
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa # v1.29.0
  hooks:
  - id: zizmor
    args:
    - --no-progress
    - --persona=auditor
- repo: https://github.com/tcort/markdown-link-check
  rev: 275c27c5035a5b4a656fe0e21a4c1403c118c767 # v3.15.0
  hooks:
    - id: markdown-link-check
      args: [--verbose, --config, .markdown-links-config.json]
- repo: local
  hooks:
  - id: bicep-lint
    name: bicep file linter
    entry: make bicep-lint
    language: system
    files: ^.*\.bicep$
    pass_filenames: false
  - id: addcopyright
    name: Add copyright header
    entry: make add-copyright
    language: system
    files: ^.*\.(go|sh|mk|py)$
    pass_filenames: false
  - id: kubeconform-lint
    name: Lint Helm Chart
    entry: make kubeconform-lint
    language: system
    files: ^charts/latest
    pass_filenames: false
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: 99470f5e12208ff0fb17ab81c3c494f7620a1d8d # v0.11.0
  hooks:
  - id: shellcheck
