apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-example
  labels:
    app: nginx
spec:
  podManagementPolicy: Parallel  # default is OrderedReady
  serviceName: statefulset
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-cns
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/cns/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/cns
          resources:
            requests:
              cpu: 5
      volumes:
        - name: persistent-storage
          ephemeral:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 10Gi
                volumeMode: Filesystem
                accessModes:
                  - ReadWriteOnce
                storageClassName: local
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
