apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: csi-local
    app.kubernetes.io/managed-by: kustomize
  name: node-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-role
subjects:
- kind: ServiceAccount
  name: node
  namespace: system
