apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-cluster-manager-metrics-service
  labels:
    control-plane: local-csi-driver
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clusterManagerMetricsService.type }}
  selector:
    control-plane: local-csi-driver
    {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.clusterManagerMetricsService.ports | toYaml | nindent 2 }}
