apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-node
  namespace: '{{ .Release.Namespace }}'
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.daemonset.serviceAccount.annotations | nindent 4 }}
