apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}-node
  labels:
  {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.node.serviceAccount.annotations | nindent 4 }}
