apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "chart.fullname" . }}-ephemeral-webhook
  labels:
  {{- include "chart.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "chart.fullname" . }}-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /validate-pvc
  failurePolicy: Ignore
  name: pvc.acstor.azure.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - persistentvolumeclaims
    scope: Namespaced
  sideEffects: None
