apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  labels:
    app.kubernetes.io/component: webhook
  {{- include "chart.labels" . | nindent 4 }}
data:
   tls.key: ""
   tls.crt: ""
   ca-cert.pem: ""
